---
- hosts: jenkins2
  become: yes
  tasks:
    - name: To gather PUblic IP
      command: curl http://169.254.169.254/latest/meta-data/public-ipv4
      register: sekharip
    - debug: var=sekharip.stdout
